version: "3.7"

services:

  jenkins:
    image: jenkins/jenkins:lts
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    ports:
      - "8081:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock  
    networks:
      - devops-infra  
      
networks:
  devops-infra:
    name: devops-infra
