services:

  jenkins:
    image: jenkins/jenkins:lts
    extra_hosts:
      - "host.docker.internal:host-gateway"
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock